modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Cable-Tiers/issues/new/choose"
[[mods]]
modId="cabletiers"
version="${file.jarVersion}"
displayName="Cable Tiers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cable-tiers"
logoFile="example.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds a Cable Tiers."

[[dependencies.cabletiers]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cabletiers]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cabletiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"